output: lib/bindings.dart
headers:
  entry-points:
  - rust/target/bindings.h
name: LightningToolkitBindings
description: Dart bindings to call lightning toolkit functions
llvm-path:
  - '/usr/local/opt/llvm/lib/libclang.dylib'