include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    use_key_in_widget_constructors: false

analyzer:
  exclude:
    - lib/services/breez_server/generated/**
    - lib/services/lightning/greenlight/cmd.dart
    - lib/generated_plugin_registrant.dart
  errors:
    asset_directory_does_not_exist: ignore
