name: c_breez
description: Flutter app showcasing Breez SDK - Native (Greenlight Implementation).
publish_to: "none"
version: 1.2.0

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.30
  app_links: ^6.4.0
  archive: ^4.0.7
  auto_size_text: ^3.0.0
  bip39: ^1.0.6
  breez_sdk:
    git:
      url: https://github.com/breez/breez-sdk-flutter
      ref: v0.8.0
  breez_translations:
    git:
      url: https://github.com/breez/Breez-Translations
      ref: 86d0d7e1c871a4ede69d867313d796089c956385
  csv: ^6.0.0
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.4.0
  drag_and_drop_lists:
    git:
      url: https://github.com/breez/DragAndDropLists
      ref: 38cc3155a6161730b4ec476d781873afb7ec4846
  duration: ^4.0.3
  #email_validator: ^3.0.0
  extended_image: ^10.0.1
  ffi: ^2.1.4
  # Downgraded firebase plugins to a version compatible with mobile_scanner <6.0.0 to avoid bumping minimum deployment target to 15.5 on iOS
  # Doesn't support: Linux Windows
  firebase_core: ^4.0.0
  # Doesn't support: Linux Windows
  firebase_messaging: ^16.0.0
  flutter_app_group_directory: ^1.1.0
  flutter_bloc: ^9.1.1
  # Doesn't support: Linux Mac Windows
  flutter_fgbg:
    git:
      url: https://github.com/breez/flutter_fgbg.git
      ref: 976b28ff3c299836f215b6deb2003838c49a8001
  flutter_inappwebview: ^6.1.5
  flutter_rust_bridge: ">2.8.0 <=2.9.0"
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: 4a494322762af9f30820f3c63aba784d46b86b69
  git_info: ^1.1.2
  hex: ^0.2.0
  http: ^1.4.0
  hydrated_bloc: ^10.0.0
  image: ^4.5.4
  # Doesn't support: Linux Mac Windows
  image_cropper: ^9.1.0 # flutter_rust_bridge 1.82.6 depends on js ^0.6.4 and no versions of flutter_rust_bridge match >1.82.6 <2.0.0
  # Doesn't support: Linux Mac Windows
  image_picker: ^1.1.2
  ini: ^2.1.0
  intl: ^0.20.2
  # Doesn't support: Linux Mac
  local_auth: ^2.3.0
  local_auth_android: ^1.0.49
  local_auth_darwin: ^1.4.3
  logging: ^1.3.0
  mockito: ^5.4.6
  # Doesn't support: Linux Windows
  mobile_scanner: ^7.0.1
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shared_preference_app_group: ^1.1.1 # iOS Notification Service extension requirement to access shared preferences
  simple_animations: ^5.2.0
  shimmer: ^3.0.0
  synchronized: ^3.3.1
  theme_provider: ^0.6.0
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  vector_math: ^2.1.4 # vector_math is pinned to version 2.1.4 by flutter_test from the flutter SDK.
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  test: ^1.26.2

dependency_overrides:
  test_api: ^0.7.6
  # Comment-out to work with breez-sdk from git repository
  breez_sdk:
    path: ../breez-sdk-greenlight/libs/sdk-flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - assets/images/
    - assets/icons/
    - .git/
    - .git/refs/heads/
    - pubspec.lock
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
