name: c_breez
description: A new Flutter project.
publish_to: "none"
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.30
  archive: ^3.4.9
  auto_size_text: ^3.0.0
  bip39: ^1.0.6
  breez_sdk:
    git:
      url: https://github.com/breez/breez-sdk-flutter
      ref: v0.2.10
  breez_translations:
    git:
      url: https://github.com/breez/Breez-Translations
      ref: ba8d9bd644a013521389d225bb6850dcd4a2918f
  clipboard_watcher: ^0.2.0
  csv: ^5.1.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  drag_and_drop_lists: ^0.3.3
  duration: ^3.0.13
  email_validator: ^2.1.17
  extended_image: ^8.2.0
  ffi: ^2.1.0
  # Doesn't support: Linux Windows
  firebase_core: ^2.24.0
  # Doesn't support: Linux Mac Windows
  firebase_dynamic_links: ^5.4.6
  # Doesn't support: Linux Windows
  firebase_messaging: ^14.7.6
  flutter_bloc: ^8.1.3
  # Doesn't support: Linux Mac Windows
  flutter_fgbg:
    git:
      url: https://github.com/breez/flutter_fgbg.git
      ref: 976b28ff3c299836f215b6deb2003838c49a8001
  flutter_inappwebview: ^6.0.0-beta.30
  flutter_rust_bridge: 1.80.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: a16aa4deeff1c5e96c6da46da31cb0533f838d8d
  git_info: ^1.1.2
  hex: ^0.2.0
  http: ^1.1.2
  hydrated_bloc: ^9.1.2
  image: ^4.1.3
  # Doesn't support: Linux Mac Windows
  image_cropper: ^5.0.1
  # Doesn't support: Linux Mac Windows
  image_picker: ^1.0.4
  ini: ^2.1.0
  intl: ^0.18.1
  # Doesn't support: Linux Mac
  local_auth: ^2.1.7
  local_auth_android: ^1.0.35
  local_auth_ios: ^1.1.5
  logging: ^1.2.0
  mockito: ^5.4.3
  # Doesn't support: Linux Windows
  mobile_scanner: ^3.5.5
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.7
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  simple_animations: ^5.0.2
  sqflite_common_ffi: ^2.3.0+4
  sqlite3_flutter_libs: ^0.5.18
  synchronized: ^3.1.0
  theme_provider: ^0.6.0
  timeago: ^3.6.0
  # Doesn't support: Linux Mac Windows
  uni_links: ^0.5.1
  url_launcher: ^6.2.1
  vector_math: ^2.1.4
  workmanager:
    git:
      url: https://github.com/breez/flutter_workmanager.git

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  test: ^1.24.9

dependency_overrides:
  test_api: ^0.6.1
  # Comment-out to work with breez-sdk from git repository
  #breez_sdk:
  #path: ../breez-sdk/libs/sdk-flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - assets/images/
    - assets/icons/
    - .git/
    - .git/refs/heads/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
