name: c_breez
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.29
  app_settings: ^4.1.8
  archive: ^3.3.5
  auto_size_text: ^3.0.0
  basic_utils: ^5.4.2
  bip32: ^2.0.0
  bip39: ^1.0.6
  bolt11_decoder: ^1.0.1
  breez_sdk:
    path: ./packages/breez_sdk
  connectivity_plus: ^3.0.2
  cryptography: ^2.0.5
  cupertino_icons: ^1.0.5
  dart_lnurl:
    git:
      url: https://github.com/breez/dart_lnurl
  drag_and_drop_lists: ^0.3.3
  drift: ^2.2.0
  drift_dev: ^2.2.0+1
  duration: ^3.0.12
  email_validator: ^2.1.17
  extended_image: ^6.3.2
  ffi: ^2.0.1
  fimber: ^0.6.6
  fimber_io: ^0.6.6
  firebase_core: ^2.3.0
  firebase_dynamic_links: ^5.0.6
  firebase_messaging: ^14.1.1
  flutter_bloc: ^8.1.1
  flutter_fgbg:
    git:
      url: https://github.com/breez/flutter_fgbg.git
      ref: 976b28ff3c299836f215b6deb2003838c49a8001
  flutter_secure_storage: ^6.1.0
  flutter_svg: ^1.1.6
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: a16aa4deeff1c5e96c6da46da31cb0533f838d8d
  grpc: ^3.1.0
  hex: ^0.2.0
  http: ^0.13.5
  hydrated_bloc: ^9.0.0
  image: ^3.2.2
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  ini: ^2.1.0
  intl: ^0.17.0
  local_auth: ^2.1.2
  local_auth_android: ^1.0.15
  local_auth_ios: ^1.0.10
  mockito: ^5.3.2
  mobile_scanner: ^2.1.0
  package_info_plus: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.11
  pointycastle: ^3.6.2
  protobuf: ^2.1.0
  qr_flutter: ^4.0.0
  rxdart: ^0.27.7
  scan: ^1.6.0
  share_extend: ^2.0.0
  shared_preferences: ^2.0.15
  simple_animations: ^5.0.0+3
  sqflite_common_ffi: ^2.2.0+1
  sqlite3_flutter_libs: ^0.5.12
  theme_provider: ^0.5.0
  timeago: ^3.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.7
  validators: ^3.0.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  test: ^1.22.0

dependency_overrides:
  test_api: ^0.4.16
  vector_math: ^2.1.4

flutter:
  uses-material-design: true
  generate: true
  assets:    
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - conf/breez.conf
    - assets/images/
    - assets/icons/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
