name: c_breez
description: A new Flutter project.
publish_to: "none"
version: 1.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.30
  app_group_directory: ^2.0.0
  archive: ^3.4.10
  auto_size_text: ^3.0.0
  bip39: ^1.0.6
  breez_sdk:
    git:
      url: https://github.com/breez/breez-sdk-flutter
      ref: v0.2.15
  breez_translations:
    git:
      url: https://github.com/breez/Breez-Translations
      ref: 132840f2dcee3f24584c26b10d716da3fdf1f1c8
  clipboard_watcher: ^0.2.1
  csv: ^6.0.0
  connectivity_plus: ^6.0.1
  device_info_plus: ^10.0.1
  drag_and_drop_lists: ^0.3.3
  duration: ^3.0.13
  email_validator: ^2.1.17
  extended_image: ^8.2.0
  ffi: ^2.1.2
  # Doesn't support: Linux Windows
  firebase_core: ^2.27.1
  # Doesn't support: Linux Mac Windows
  firebase_dynamic_links: ^5.4.18
  # Doesn't support: Linux Windows
  firebase_messaging: ^14.7.20
  flutter_bloc: ^8.1.4
  # Doesn't support: Linux Mac Windows
  flutter_fgbg:
    git:
      url: https://github.com/breez/flutter_fgbg.git
      ref: 976b28ff3c299836f215b6deb2003838c49a8001
  flutter_inappwebview: ^6.0.0
  flutter_rust_bridge: ^1.82.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: a16aa4deeff1c5e96c6da46da31cb0533f838d8d
  git_info: ^1.1.2
  hex: ^0.2.0
  http: ^1.2.1
  hydrated_bloc: ^9.1.4
  image: ^4.1.7
  # Doesn't support: Linux Mac Windows
  image_cropper: ^5.0.1
  # Doesn't support: Linux Mac Windows
  image_picker: ^1.0.7
  ini: ^2.1.0
  intl: ^0.19.0
  # Doesn't support: Linux Mac
  local_auth: ^2.2.0
  local_auth_android: ^1.0.37
  local_auth_darwin: ^1.2.2
  logging: ^1.2.0
  mockito: ^5.4.4
  # Doesn't support: Linux Windows
  mobile_scanner: ^4.0.1
  package_info_plus: ^6.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  shared_preference_app_group: ^1.0.0+1 # iOS Notification Service extension requirement to access shared preferences
  simple_animations: ^5.0.2
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.20
  synchronized: ^3.1.0+1
  theme_provider: ^0.6.0
  timeago: ^3.6.1
  # Doesn't support: Linux Mac Windows
  uni_links: ^0.5.1
  url_launcher: ^6.2.5
  vector_math: ^2.1.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  test: ^1.25.2

dependency_overrides:
  test_api: ^0.7.0
  intl: ^0.19.0 # intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.
  # Comment-out to work with breez-sdk from git repository
  breez_sdk:
    path: ../breez-sdk/libs/sdk-flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - assets/images/
    - assets/icons/
    - .git/
    - .git/refs/heads/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
