name: c_breez
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.30
  archive: ^3.3.7
  auto_size_text: ^3.0.0
  bip39: ^1.0.6
  breez_sdk:
    path: ../breez-sdk/libs/sdk-flutter
  breez_translations:
    git:
      url: https://github.com/breez/Breez-Translations
      ref: b610d54ad7c105258afb6dd8da0075ccba765cd6
  clipboard_watcher: ^0.2.0
  connectivity_plus: ^4.0.1
  drag_and_drop_lists: ^0.3.3
  duration: ^3.0.12
  email_validator: ^2.1.17
  extended_image: <8.0.0 # Requires Flutter 3.10
  ffi: ^2.0.2
  fimber: ^0.6.6
  fimber_io: ^0.6.6
  # Doesn't support: Linux Mac Windows
  flutter_fimber: ^0.6.5
  # Doesn't support: Linux Windows
  firebase_core: ^2.13.1
  # Doesn't support: Linux Mac Windows
  firebase_dynamic_links: ^5.3.2
  # Doesn't support: Linux Windows
  firebase_messaging: ^14.6.2
  flutter_bloc: ^8.1.3
  # Doesn't support: Linux Mac Windows
  flutter_fgbg:
    git:
      url: https://github.com/breez/flutter_fgbg.git
      ref: 976b28ff3c299836f215b6deb2003838c49a8001
  flutter_inappwebview: ^6.0.0-beta.23
  flutter_rust_bridge: 1.75.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: <2.0.6 # Requires Flutter 3.10
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: a16aa4deeff1c5e96c6da46da31cb0533f838d8d
  hex: ^0.2.0
  http: <1.0.0 # Requires Flutter 3.10
  hydrated_bloc: ^9.1.1
  image: ^4.0.17
  # Doesn't support: Linux Mac Windows
  image_cropper: ^4.0.1
  # Doesn't support: Linux Mac Windows
  image_picker: ^0.8.7+5
  ini: ^2.1.0
  intl: ^0.18.1
  # Doesn't support: Linux Mac
  local_auth: ^2.1.6
  local_auth_android: ^1.0.30
  local_auth_ios: ^1.1.3
  mockito: <5.4.1
  # Doesn't support: Linux Windows
  mobile_scanner: ^3.2.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  share_plus: ^7.0.2
  shared_preferences: ^2.1.1
  simple_animations: ^5.0.1
  sqflite_common_ffi: ^2.2.5
  sqlite3_flutter_libs: ^0.5.15
  synchronized: ^3.1.0
  theme_provider: ^0.6.0
  timeago: ^3.4.0
  # Doesn't support: Linux Mac Windows
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  vector_math: ^2.1.4
  workmanager:
    git:
      url: https://github.com/breez/flutter_workmanager.git

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: <2.4.0 # Requires Flutter 3.10
  flutter_lints: ^2.0.1
  test: <1.24.0 # Requires Flutter 3.10

dependency_overrides:
  archive: ^3.3.7
  intl: ^0.18.1
  path: ^1.8.3
  test_api: <0.5.0 # Requires Flutter 3.10

flutter:
  uses-material-design: true
  generate: true
  assets:
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - conf/breez.conf
    - assets/images/
    - assets/icons/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
