name: c_breez
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.10.29
  app_settings: ^4.1.8
  archive: ^3.3.0
  auto_size_text: ^3.0.0
  basic_utils: ^4.4.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  bolt11_decoder: ^1.0.1
  cryptography: ^2.0.5
  cupertino_icons: ^1.0.5
  dart_lnurl:
    git:
      url: https://github.com/breez/dart_lnurl
  drag_and_drop_lists: # Target this ref until new release
    git:
      url: https://github.com/mauriceraguseinit/DragAndDropLists
      ref: 2b9660e90b073de4bf7510ba98140f778e846f2e
  drift: ^1.7.1
  duration: ^3.0.11
  email_validator: ^2.0.1
  extended_image: ^6.2.1
  fimber: ^0.6.6
  fimber_io: ^0.6.6
  firebase_core: ^1.19.2
  firebase_dynamic_links: ^4.3.2
  firebase_messaging: ^12.0.0
  fixnum: ^1.0.1
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.1+1
  flutter_typeahead: ^4.0.0
  grpc: ^3.0.2
  hex: ^0.2.0
  http: ^0.13.4
  hydrated_bloc: ^8.1.0
  image: ^3.2.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  ini: ^2.1.0
  intl: ^0.17.0
  local_auth: ^2.1.0
  local_auth_android: ^1.0.6
  local_auth_ios: ^1.0.7
  mobile_scanner: ^2.0.0
  package_info_plus: ^1.4.2
  path: ^1.8.1
  path_provider: ^2.0.11
  pointycastle: ^3.6.1
  protobuf: ^2.1.0
  qr_flutter: ^4.0.0
  rxdart: ^0.27.5
  scan: ^1.6.0
  share_extend: ^2.0.0
  shared_preferences: ^2.0.15
  simple_animations: ^4.2.0
  sqlite3_flutter_libs: ^0.5.8
  timeago: ^3.2.2
  uni_links: ^0.5.1
  url_launcher: ^6.1.5
  validators: ^3.0.0
  breez_sdk:
    path: ./packages/breez_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  drift_dev: ^1.7.0
  flutter_lints: ^2.0.1
  mockito: ^5.2.0
  sqflite_common_ffi: ^2.1.1+1
  test: ^1.21.4

dependency_overrides:
  test_api: 0.4.12

flutter:
  uses-material-design: true
  generate: true
  assets:    
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - conf/breez.conf
    - assets/images/
    - assets/icons/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
