[package]
name = "lightning_toolkit"
version = "0.1.0"
edition = "2021"

[lib]
name = "lightning_toolkit"
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "1"
anyhow = { version = "1.0.57", features = ["backtrace"] }
hex = "*"
bitcoin_hashes = "*"
# Note: private repo, might need git credentials helper to be setup
# If so, see https://techexpertise.medium.com/storing-git-credentials-with-git-credential-helper-33d22a6b5ce7
# Using vls-v0.11.0.1 branch for VLS integration
gl-client = { git = "https://github.com/Blockstream/greenlight", branch="vls-v0.11.0.1" }
lightning-signer-core = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
lightning-signer-server = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-protocol-signer = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-protocol = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-persist = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-proxy = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
base64 = "0.13.0"
ecies = {version = "0.2", default-features = false, features = ["pure"]}
once_cell = "*"
ripemd = "*"
rand = "*"
tiny-bip39 = "*"
tokio = "*"
rusqlite = { version = "0.28.0", features = ["bundled"] }
rusqlite_migration = "*"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"