[package]
name = "lightning_toolkit"
version = "0.1.0"
edition = "2021"

[lib]
name = "lightning_toolkit"
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "1"
anyhow = { version = "1.0.57", features = ["backtrace"] }
hex = "*"
bitcoin_hashes = "*"
lightning-signer-core = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
lightning-signer-server = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-protocol-signer = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-protocol = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-persist = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-proxy = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
base64 = "0.13.0"
ecies = {version = "0.2", default-features = false, features = ["pure"]}
ripemd = "*"
rand = "*"