[package]
name = "lightning_toolkit"
version = "0.1.0"
edition = "2021"

[lib]
name = "lightning_toolkit"
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "1"
lightning-invoice = "0.14.0"
anyhow = { version = "1.0.57", features = ["backtrace"] }
hex = "*"
bitcoin_hashes = { version = "0.10.0", default-features = false }
lightning-signer-core = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-protocol-signer = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }
vls-protocol = { git="https://gitlab.com/lightning-signer/validating-lightning-signer.git", branch="main" }