[package]
name = "breez-sdk-bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "breez_sdk_bindings"
crate-type = ["staticlib", "cdylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning_toolkit = { path = "../rust"}
anyhow = { version = "1.0.57", features = ["backtrace"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
uniffi = "0.21.0"
uniffi_macros = "0.21.0"
lightning-invoice = "*"
log = "*"
once_cell = "*"
flutter_rust_bridge = "1"
tiny-bip39 = "*"
tonic = { version = "^0.8", features = ["tls", "tls-roots", "tls-webpki-roots"] }

[build-dependencies]
uniffi_build = "0.21.0"
anyhow = { version = "1.0.57", features = ["backtrace"] }