// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJWsGJcsK2U9BcYahortPZ7epzKmDcU8',
    appId: '1:463327817067:android:73e1216321b4fc03b2b02e',
    messagingSenderId: '463327817067',
    projectId: 'breez-technology',
    databaseURL: 'https://breez-technology.firebaseio.com',
    storageBucket: 'breez-technology.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqioSI--u4sgqj58qI9gDAnxpp1zOLN8Y',
    appId: '1:463327817067:ios:7899861f17b00f57b2b02e',
    messagingSenderId: '463327817067',
    projectId: 'breez-technology',
    databaseURL: 'https://breez-technology.firebaseio.com',
    storageBucket: 'breez-technology.appspot.com',
    androidClientId: '463327817067-18vj3qv2bqh0k2ql9b55fbpkih59ld84.apps.googleusercontent.com',
    iosClientId: '463327817067-abe9qr1ls86ua9n6jvgs5eofcjadfsoq.apps.googleusercontent.com',
    iosBundleId: 'com.cBreez.client',
  );
}
