name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with: 
          path: 'cbreez'

      - uses: actions/checkout@v3
        with:         
          repository: 'breez/breez-sdk'                   
          ssh-key: ${{secrets.REPO_SSH_KEY}}          
          path: 'breez-sdk'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'          

      - name: install dependencies
        run: |          
          cargo install cargo-ndk          
          brew install protobuf
          cd breez-sdk/sdk-flutter
          make init

      - name: build sdk
        env:
          SSH_PRIVATE_KEY: ${{secrets.REPO_SSH_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          cd breez-sdk/sdk-flutter
          make android

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'      

      - name: flutter-doctor
        run: |
          cd cbreez
          flutter doctor

      - name: pub-get
        run: |
          cd cbreez
          flutter pub get

      - name: build-apk
        run: |
          cd cbreez
          flutter build apk --split-per-abi

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: c-breez
          path: cbreez/build/app/outputs/flutter-apk/app-*.apk
