name: Merge Pull Request

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dart-format:
    if: github.event.pull_request.merged == true
    runs-on: macOS-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been merged
          cd cbreez
          dart format --fix -l 110 . && git add . && git commit -m "Reformat code with 'dart format'"
