name: Verify Breez SDK - Native (Greenlight Implementation) Files
on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Verify Breez SDK - Native (Greenlight Implementation) Files
    runs-on: macOS-15
    steps:
      - name: Disk Cleanup
        run: |
          echo "::group::Free space before cleanup"
          df -hI
          echo "::endgroup::"
          echo "::group::Cleaned Files"
          sudo rm -rf /Users/runner/Library/Android/sdk
          sudo rm -rf /Applications/Xcode_15.4.app
          sudo rm -rf /Applications/Xcode_16.1.app
          sudo rm -rf /Applications/Xcode_16.2.app
          sudo rm -rf /Applications/Xcode_16.3_Release_Candidate_2.app
          echo "::endgroup::"
          echo "::group::Free space after cleanup"
          df -hI
          echo "::endgroup::"

      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - name: 🏗️ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🏗️ Setup breez-sdk-greenlight repository
        uses: actions/checkout@v4
        with:
          repository: 'breez/breez-sdk-greenlight'
          ssh-key: ${{secrets.REPO_SSH_KEY}}
          path: 'breez-sdk-greenlight'
          ref: 'main'

      - name: 🏗️ Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: breez-sdk-greenlight/libs
          cache-all-crates: true

      - name: 📦 Install Breez SDK - Native (Greenlight Implementation) dependencies
        working-directory: breez-sdk-greenlight/libs/
        run: |
          brew install protobuf
          cd sdk-bindings
          make init

      - name: 🔨 Build Breez SDK - Native (Greenlight Implementation)
        working-directory: breez-sdk-greenlight/libs/sdk-bindings
        run: |
          rm -rf ../target
          cargo check
          make ios-universal

      - name: Verify iOS library files
        working-directory: breez-sdk-greenlight/libs
        run: |
          if [ ! -f "../target/aarch64-apple-ios/release/libbreez_sdk_bindings.a" ]; then
            echo "Error: aarch64-apple-ios library not found!"
            exit 1
          else
            echo "Success: aarch64-apple-ios library found!"
            ls -la ../target/aarch64-apple-ios/release/
          fi
          
          if [ ! -f "../target/ios-universal/release/libbreez_sdk_bindings.a" ]; then
            echo "Error: Universal iOS library not found!"
            exit 1
          else
            echo "Success: Universal iOS library found!"
            ls -la ../target/ios-universal/release/
          fi